--------------------------------------------------------
--  File created - Sunday-March-01-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ADMIN
--------------------------------------------------------

  CREATE TABLE "DBUSER"."ADMIN" 
   (	"ADMIN_ID" NUMBER(*,0), 
	"NAME" VARCHAR2(50 BYTE), 
	"PASSWORD" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into DBUSER.ADMIN
SET DEFINE OFF;
Insert into DBUSER.ADMIN (ADMIN_ID,NAME,PASSWORD) values (9,'sami','566');
Insert into DBUSER.ADMIN (ADMIN_ID,NAME,PASSWORD) values (6,'barsha','12345');
Insert into DBUSER.ADMIN (ADMIN_ID,NAME,PASSWORD) values (29,'barsha robbani','123456');
Insert into DBUSER.ADMIN (ADMIN_ID,NAME,PASSWORD) values (34,'shahriar','123456789');
Insert into DBUSER.ADMIN (ADMIN_ID,NAME,PASSWORD) values (4,'explorerone','password');
Insert into DBUSER.ADMIN (ADMIN_ID,NAME,PASSWORD) values (10,'shahriarrobbani','82664442');
--------------------------------------------------------
--  DDL for Index ADMIN_INDEX1
--------------------------------------------------------

  CREATE UNIQUE INDEX "DBUSER"."ADMIN_INDEX1" ON "DBUSER"."ADMIN" ("ADMIN_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table ADMIN
--------------------------------------------------------

  ALTER TABLE "DBUSER"."ADMIN" ADD CONSTRAINT "ADMIN_PK" PRIMARY KEY ("ADMIN_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DBUSER"."ADMIN" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "DBUSER"."ADMIN" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "DBUSER"."ADMIN" MODIFY ("ADMIN_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  DDL for Trigger T_ADMIN_ID
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "DBUSER"."T_ADMIN_ID" 
BEFORE INSERT
ON ADMIN
REFERENCING NEW AS NEW
FOR EACH ROW
BEGIN
  if(:new.ADMINID is null) then
  SELECT S_ADMIN.nextval
  INTO :new.ADMINID
  FROM dual;
  end if;
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ADMINID IS NULL THEN
      SELECT S_ADMIN.NEXTVAL INTO :NEW.ADMINID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "DBUSER"."T_ADMIN_ID" ENABLE;
